### ISSUE TITLE
browserhistory python module doesnot work ( NameError: name 'dict_keys' is not defined)

### ISSUE THREAD

**Issue by mddas** [kcp18/browserhistory#10]
python -m pip install browserhistory.
i install browserhistory module in python 3.6.1 on windows
it installed correctly.

>>>import browserhistory as bh
>>>dict_obj = bh.get_browserhistory()
>>>dict_obj.keys()
dict_keys(['chrome'])
>>>dict_keys(['safari', 'chrome', 'firefox'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'dict_keys' is not defined

**Comment by FilippoDeAngelis** [comment]
The dict_keys() line in the examples is supposed to be the output to the dict_obj.keys() function call. This could be made clearer

**Comment by rajgupta81** [comment]
import browserhistory as bh
dict_obj = bh.get_browserhistory()
data = dict_obj.keys()
print(data)
data = dict_obj['chrome'][0]
print(data)

dict_keys([])
Traceback (most recent call last):
  File "/home/raj/Desktop/anilyzer/myproject/main.py", line 6, in <module>
    data = dict_obj['chrome'][0]
KeyError: 'chrome'

can anyone please help!!

**Comment by rajgupta81** [comment]
the module browserhistory is not properly maintained so i have done some changes you can use that file in liniux 

https://github.com/rajgupta81/browserhistory
